In [16]:
import cv2
import os
import time
import glob
import numpy as np
from scipy import misc
import PIL.Image
import io

data_folder = 'E:/Tests/1/'
save_folder = 'E:/Tests/1/out/'

for file in os.listdir(data_folder):
    filename = os.fsdecode(file)
    if filename.endswith(".png"): 
        img = os.path.join(data_folder, filename)
        save_path = os.path.join(save_folder, filename)
        
        img = cv2.imread(img, 1)
        
        # Read the image
        height, width, channels = img.shape

        # Cut the image in half
        width_cutoff = width // 2
        s1 = img
        s2 = img
        
        # convert to hsv
        hsv = cv2.cvtColor(s2, cv2.COLOR_BGR2HSV)
        
        # lower mask (0-10)
        lower_red = np.array([0,0,5])
        upper_red = np.array([100,100,100])
        mask0 = cv2.inRange(hsv, lower_red, upper_red)

        # upper mask (170-180)
        lower_red = np.array([0,0,5])
        upper_red = np.array([0,0,95])
        mask1 = cv2.inRange(hsv, lower_red, upper_red)

        # join my masks
        mask = mask0+mask1

        # set my output img to zero everywhere except my mask
        output_img = img.copy()
        output_img[np.where(mask==0)] = 0
        
        transparent_img = cv2.cvtColor(output_img, cv2.COLOR_HSV2BGR)
        transparent_img = cv2.cvtColor(output_img, cv2.COLOR_BGR2BGRA)
        
        transparent_img[np.where(mask==0)] = 0
        
        print(transparent_img)
        
        is_success, target_png = cv2.imencode('.png', transparent_img)

        buf = io.BytesIO(target_png)
        buf.seek(0)
        
        img_mask = PIL.Image.open(buf)
        
        img_mask.save(save_path,'PNG')

        buf.close()
        
        print('saved ' + filename)
        
        continue
    else:
        continue
        
        
        
'''     #Red masks        
        # lower mask (0-10)
        lower_red = np.array([0,50,50])
        upper_red = np.array([10,255,255])
        mask0 = cv2.inRange(hsv, lower_red, upper_red)
        
        # upper mask (170-180)
        lower_red = np.array([170,50,50])
        upper_red = np.array([180,255,255])
        mask1 = cv2.inRange(hsv, lower_red, upper_red)
'''

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
saved index.png


'     #Red masks        \n        # lower mask (0-10)\n        lower_red = np.array([0,50,50])\n        upper_red = np.array([10,255,255])\n        mask0 = cv2.inRange(hsv, lower_red, upper_red)\n        \n        # upper mask (170-180)\n        lower_red = np.array([170,50,50])\n        upper_red = np.array([180,255,255])\n        mask1 = cv2.inRange(hsv, lower_red, upper_red)\n'